

const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENTS = "NEW_ATTACHMENTS";
const NEW_MESSAGES_ALERT = "NEW_MESSAGES_ALERT";

const NEW_REQUEST = 'NEW_REQUEST'

const NEW_MESSAGE = 'NEW_MESSAGE'



export { ALERT, REFETCH_CHATS, NEW_ATTACHMENTS, NEW_MESSAGES_ALERT, NEW_REQUEST, NEW_MESSAGE };